//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    public partial class Cliente : ServiceReference1.Empresa
    {
        
        private bool BloqueadoField;
        
        private string RazonBloqueoField;
        
        private ServiceReference1.SucursalCliente[] SucursalesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bloqueado
        {
            get
            {
                return this.BloqueadoField;
            }
            set
            {
                this.BloqueadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonBloqueo
        {
            get
            {
                return this.RazonBloqueoField;
            }
            set
            {
                this.RazonBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SucursalCliente[] Sucursales
        {
            get
            {
                return this.SucursalesField;
            }
            set
            {
                this.SucursalesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Proveedor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Cliente))]
    public partial class Empresa : object
    {
        
        private string Apellido1Field;
        
        private string Apellido2Field;
        
        private string DvField;
        
        private string IdField;
        
        private string NombresField;
        
        private string RazonSocialField;
        
        private string TipoDocumentoField;
        
        private int TipoPersonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1
        {
            get
            {
                return this.Apellido1Field;
            }
            set
            {
                this.Apellido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2
        {
            get
            {
                return this.Apellido2Field;
            }
            set
            {
                this.Apellido2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dv
        {
            get
            {
                return this.DvField;
            }
            set
            {
                this.DvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoPersona
        {
            get
            {
                return this.TipoPersonaField;
            }
            set
            {
                this.TipoPersonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    public partial class Proveedor : ServiceReference1.Empresa
    {
        
        private ServiceReference1.SucursalProveedor[] SucursalesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SucursalProveedor[] Sucursales
        {
            get
            {
                return this.SucursalesField;
            }
            set
            {
                this.SucursalesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SucursalCliente", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    public partial class SucursalCliente : ServiceReference1.Sucursal
    {
        
        private bool ManejaIvaField;
        
        private string TipoClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ManejaIva
        {
            get
            {
                return this.ManejaIvaField;
            }
            set
            {
                this.ManejaIvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCliente
        {
            get
            {
                return this.TipoClienteField;
            }
            set
            {
                this.TipoClienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SucursalProveedor", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    public partial class SucursalProveedor : ServiceReference1.Sucursal
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sucursal", Namespace="http://schemas.datacontract.org/2004/07/Consultas")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SucursalCliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SucursalProveedor))]
    public partial class Sucursal : object
    {
        
        private string CiudadField;
        
        private string CondicionPagoField;
        
        private string DepartamentoField;
        
        private string DirecciónField;
        
        private string IdField;
        
        private string IdCiudadField;
        
        private string IdDepartamentoField;
        
        private string IdPaisField;
        
        private string MonedaField;
        
        private string PaisField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CondicionPago
        {
            get
            {
                return this.CondicionPagoField;
            }
            set
            {
                this.CondicionPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirección
        {
            get
            {
                return this.DirecciónField;
            }
            set
            {
                this.DirecciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCiudad
        {
            get
            {
                return this.IdCiudadField;
            }
            set
            {
                this.IdCiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais
        {
            get
            {
                return this.IdPaisField;
            }
            set
            {
                this.IdPaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IConsulta")]
    public interface IConsulta
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsulta/GetClientes", ReplyAction="http://tempuri.org/IConsulta/GetClientesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cliente[]> GetClientesAsync(string documento, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsulta/GetProveedores", ReplyAction="http://tempuri.org/IConsulta/GetProveedoresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedoresAsync(string documento, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsulta/GetClientes_N", ReplyAction="http://tempuri.org/IConsulta/GetClientes_NResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cliente[]> GetClientes_NAsync(string Documento, string RazonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsulta/GetProveedores_N", ReplyAction="http://tempuri.org/IConsulta/GetProveedores_NResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedores_NAsync(string documento, string razonSocial);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IConsultaChannel : ServiceReference1.IConsulta, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ConsultaClient : System.ServiceModel.ClientBase<ServiceReference1.IConsulta>, ServiceReference1.IConsulta
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConsultaClient() : 
                base(ConsultaClient.GetDefaultBinding(), ConsultaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConsulta.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaClient(EndpointConfiguration endpointConfiguration) : 
                base(ConsultaClient.GetBindingForEndpoint(endpointConfiguration), ConsultaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConsultaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConsultaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cliente[]> GetClientesAsync(string documento, string razonSocial)
        {
            return base.Channel.GetClientesAsync(documento, razonSocial);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedoresAsync(string documento, string razonSocial)
        {
            return base.Channel.GetProveedoresAsync(documento, razonSocial);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cliente[]> GetClientes_NAsync(string Documento, string RazonSocial)
        {
            return base.Channel.GetClientes_NAsync(Documento, RazonSocial);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedores_NAsync(string documento, string razonSocial)
        {
            return base.Channel.GetProveedores_NAsync(documento, razonSocial);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsulta))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsulta))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.100.45/SiesaLabroides/Consultas.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConsulta);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConsulta);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConsulta,
        }
    }
}
